### ISSUE TITLE
Requesting an additional robotframework library providing UDS keywords

### ISSUE THREAD

**Issue by lxndrttz** [test-fullautomation/robotframework-uds#1]
Current state:
robotframework-doip library covers the transport layer of UDS standard. It is possible to send UDS requests and get responses on automothive ethernet. But requests have to be encoded and responses decoded by the user.

Requested state:
With an additional robotframework library for UDS applicatoin layer (which utilizes DoIP or CAN transport layer) it would be possible to write UDS oriented tests instead of protocol specific tests. The new library should cover keywords like ...

* Build payload
* Send the request
* Waits for a response, with timeout
* Interpret response data
* Validate response content

Note:
There is already a python module around which offers a connector to 'doipclient' module (robotframework-doip). It is 'udsoncan'.

https://python-doipclient.readthedocs.io/en/latest/connectors.html
https://udsoncan.readthedocs.io/en/latest/

Maybe it is possible to create a robotframework library based on 'udsoncan' module?

**Comment by trimai3001** [comment]
I have the initial version of the UDS demo, so Alex will need a few days to review it and provide feedback

**Comment by trimai3001** [comment]
Hi Thomas, 
The UDS keywords are complete, and I will provide updates if the user has any feedback in the future.
Thank you,
Tri

**Comment by test-fullautomation** [comment]
UDS keyword library is part of 0.13.1
