### ISSUE TITLE
write_data_by_name required

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-uds#23]
In our UDS keyword library, we have keywords for `read_data_by_identifier` and `read_data_by_name`. But on the other hand, only `write_data_by_identifier` is available. However, I only know the UDS commands and not their DID. Therefore, we still need a `write_data_by_name` keyword.

**Comment by trimai3001** [comment]
Hi @test-fullautomation,
I am beginning to investigate and work on the implementation of this issue.
Thank you,
Tri

**Comment by test-fullautomation** [comment]
Hi @trimai3001 ,
very good! It's important for the MPCI project.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi @trimai3001 ,
after discussion with the MPCI project this should have highest priority.
Currently test-case implementation is dependent on this feature.
Thank you,
 Thomas

**Comment by trimai3001** [comment]
Integrated in RobotFramework AIO 0.13.1
