### ISSUE TITLE
add readme.md, setup.py, documentation, release_info

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-uds#4]
Once @HolQue added infrastructure for readme.md, setup.py, documentation and release_info, please add this, too.

_Originally posted by @test-fullautomation in https://github.com/test-fullautomation/robotframework-uds/pull/2#pullrequestreview-2229625765_

**Comment by trimai3001** [comment]
Hi Thomas,
All the documents have been added, and I'm currently updating the docstrings for all the methods.
Thank you,
Tri
